MiniBook/MiniBook/Controllers/AuthorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MiniBook.Models;

namespace MiniBook.Controllers
{
    public class AuthorController : Controller
    {
        private BOOKSTOREEntities db = new BOOKSTOREEntities();

        // GET: Author
        public ActionResult Index()
        {
            if (Session["Admin"] == null)
                return RedirectToAction("Login", "Admin");
            return View(db.TACGIAs.ToList());
        }

        // GET: Author/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["Admin"] == null)
                return RedirectToAction("Login", "Admin");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TACGIA tACGIA = db.TACGIAs.Find(id);
            if (tACGIA == null)
            {
                return HttpNotFound();
            }
            return View(tACGIA);
        }

        // GET: Author/Create
        public ActionResult Create()
        {
            if (Session["Admin"] == null)
                return RedirectToAction("Login", "Admin");
            return View();
        }

        // POST: Author/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDTG,Ten,DiaChi,Mail,GioiThieu")] TACGIA tACGIA)
        {
            if (ModelState.IsValid)
            {
                db.TACGIAs.Add(tACGIA);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tACGIA);
        }

        // GET: Author/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["Admin"] == null)
                return RedirectToAction("Login", "Admin");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TACGIA tACGIA = db.TACGIAs.Find(id);
            if (tACGIA == null)
            {
                return HttpNotFound();
            }
            return View(tACGIA);
        }

        // POST: Author/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDTG,Ten,DiaChi,Mail,GioiThieu")] TACGIA tACGIA)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tACGIA).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tACGIA);
        }

        // GET: Author/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["Admin"] == null)
                return RedirectToAction("Login", "Admin");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TACGIA tACGIA = db.TACGIAs.Find(id);
            if (tACGIA == null)
            {
                return HttpNotFound();
            }
            return View(tACGIA);
        }

        // POST: Author/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TACGIA tACGIA = db.TACGIAs.Find(id);
            db.TACGIAs.Remove(tACGIA);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MiniBook/MiniBook/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MiniBook.Models;

namespace MiniBook.Controllers
{
    public class BookController : Controller
    {
        private BOOKSTOREEntities db = new BOOKSTOREEntities();

        // GET: Book
        public ActionResult Index()
        {
            if (Session["Admin"] == null)
                return RedirectToAction("Login", "Admin");
            var sACHes = db.SACHes.Include(s => s.NXB).Include(s => s.THELOAI);
            return View(sACHes.ToList());
        }

        // GET: Book/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["Admin"] == null)
                return RedirectToAction("Login", "Admin");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SACH sACH = db.SACHes.Find(id);
            if (sACH == null)
            {
                return HttpNotFound();
            }
            return View(sACH);
        }

        // GET: Book/Create
        public ActionResult Create()
        {
            if (Session["Admin"] == null)
                return RedirectToAction("Login", "Admin");
            ViewBag.IDNXB = new SelectList(db.NXBs, "IDNXB", "TenNXB");
            ViewBag.IDTheLoai = new SelectList(db.THELOAIs, "IDTheLoai", "TenTheLoai");
            return View();
        }

        // POST: Book/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDSach,TenSach,GiaBan,SoLuongKho,MoTa,AnhMinhHoa,NgayPhatHanh,SLXem,SLBan,IDNXB,IDTheLoai")] SACH sACH, HttpPostedFileBase AnhMinhHoa)
        {
            if (AnhMinhHoa!=null)
            {
                var fileName = Path.GetFileName(AnhMinhHoa.FileName);
                var path = Path.Combine(Server.MapPath("~/Images"), fileName);
                if (System.IO.File.Exists(path))
                {
                    ViewBag.ThongBao = "Ảnh đã tồn tại";
                }
                else
                {
                    AnhMinhHoa.SaveAs(path);
                }
                if (ModelState.IsValid)
                {
                    sACH.AnhMinhHoa = fileName;
                    db.SACHes.Add(sACH);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                ViewBag.IDNXB = new SelectList(db.NXBs, "IDNXB", "SDT", sACH.IDNXB);
                ViewBag.IDTheLoai = new SelectList(db.THELOAIs, "IDTheLoai", "TenTheLoai", sACH.IDTheLoai);
                return View(sACH);
            }
            ViewBag.ThongBao = "Vui lòng điền đầy đủ thông tin";
            return View();
            
        }

        // GET: Book/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["Admin"] == null)
                return RedirectToAction("Login", "Admin");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SACH sACH = db.SACHes.Find(id);
            if (sACH == null)
            {
                return HttpNotFound();
            }
            ViewBag.IDNXB = new SelectList(db.NXBs, "IDNXB", "SDT", sACH.IDNXB);
            ViewBag.IDTheLoai = new SelectList(db.THELOAIs, "IDTheLoai", "TenTheLoai", sACH.IDTheLoai);
            return View(sACH);
        }

        // POST: Book/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDSach,TenSach,GiaBan,SoLuongKho,MoTa,AnhMinhHoa,NgayPhatHanh,SLXem,SLBan,IDNXB,IDTheLoai")] SACH sACH, HttpPostedFileBase AnhMinhHoa)
        {   
            if (ModelState.IsValid)
            {
                var sachDB = db.SACHes.FirstOrDefault(s => s.IDSach == sACH.IDSach);
                var fileName = Path.GetFileName(AnhMinhHoa.FileName);
                var path = Path.Combine(Server.MapPath("~/Images"), fileName);
                sACH.AnhMinhHoa = fileName;
                AnhMinhHoa.SaveAs(path);

                sachDB.TenSach = sACH.TenSach;
                sachDB.GiaBan = sACH.GiaBan;
                sachDB.SoLuongKho = sACH.SoLuongKho;
                sachDB.MoTa =sACH.MoTa;
                sachDB.AnhMinhHoa = sACH.AnhMinhHoa;
                sachDB.NgayPhatHanh = sACH.NgayPhatHanh;
                sachDB.SLXem=sACH.SLXem;
                sachDB.SLBan=sACH.SLBan;
                sachDB.IDNXB = sACH.IDNXB;
                sachDB.IDTheLoai = sACH.IDTheLoai;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IDNXB = new SelectList(db.NXBs, "IDNXB", "SDT", sACH.IDNXB);
            ViewBag.IDTheLoai = new SelectList(db.THELOAIs, "IDTheLoai", "TenTheLoai", sACH.IDTheLoai);
            return View(sACH);
        }

        // GET: Book/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["Admin"] == null)
                return RedirectToAction("Login", "Admin");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SACH sACH = db.SACHes.Find(id);
            if (sACH == null)
            {
                return HttpNotFound();
            }
            return View(sACH);
        }

        // POST: Book/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SACH sACH = db.SACHes.Find(id);
            db.SACHes.Remove(sACH);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MiniBook/MiniBook/Controllers/MBookController.cs
using Microsoft.Ajax.Utilities;
using MiniBook.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
namespace MiniBook.Controllers
{
    public class MBookController : Controller
    {
        BOOKSTOREEntities db = new BOOKSTOREEntities();
        // GET: MBook
        private List<SACH> TopSaleBooks(int soluong)
        {
            return db.SACHes.OrderByDescending(sach =>sach.SLBan).Take(soluong).ToList();
        }

        public ActionResult Index()
        {
            var sp = TopSaleBooks(4);
            return View(sp);
        }
        public ActionResult AllBook(string searchString, int ? page)
        {
            int pageSize = 8;
            int pageNum = (page ?? 1);
            var sachs = db.SACHes.OrderByDescending(sach => sach.NgayPhatHanh).ToList();
            if(searchString != null)
            {
                sachs = db.SACHes.Where(s =>s.TenSach.Contains(searchString)).ToList();

            }

            return View(sachs.ToPagedList(pageNum,pageSize));
        }
        public ActionResult GetCategories ()
        {
            var c =db.THELOAIs.ToList();
            return PartialView(c); 
        }
        public ActionResult BookForCate(int id, int ? page)
        {
            int pageSize = 8;
            int pageNum = (page ?? 1);
            var books =db.SACHes.Where( b=> b.IDTheLoai == id).ToList();
            return View("AllBook",books.ToPagedList(pageNum,pageSize));
        }
        public ActionResult Details (int id)
        {
            var book = db.SACHes.FirstOrDefault(b => b.IDSach == id);
            return View(book);
        }
    }
}

MiniBook/MiniBook/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()
    </body>
</html>

MiniBook/MiniBook/Views/Shared/_LayoutAdmin.cshtml
    <!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8">
    <title>@ViewBag.Title</title>
    <link href="~\Content\bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    @Styles.Render("~/Content/portal.css")
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    
    <style>
        .navigation {
            float: right;
            display: block;
            margin: 5px 150px 0 0;
            
        }
        .nav-item .nav-link {
            background-color: steelblue;
            border: 3px solid;
            border-color: blanchedalmond;
            color: blanchedalmond;
            font-weight: 500;
            font-size: 20px;
        }

    </style>
</head>
<body>
    <div>

        <div class="app-sidepanel"style="background-color: steelblue; ">
            <div class="app-branding" >
                <a href="@Url.Action("Index","Admin")">
                    <img class="logo-icon me-2" src="~/Images/Logo1.png" alt="logo" style="width:100%;">
                </a>
            </div>
            <div class="sidepanel-drop"></div>
            <div class="sidepanel-inner d-flex flex-column">
                <nav class="app-nav app-nav-main flex-grow-1" , style="background-color: steelblue; border-top: 3px solid; border-color: blanchedalmond; ">
                    <ul class="app-menu list-unstyled ">
                        @if (Session["Admin"] != null)
                        {
                            <li class="nav-item " style="color: white;">
                                <ul class="nav-link dropdown-toggle " data-bs-toggle="dropdown">@Session["AdminName"]</ul>
                                <ul class="dropdown-menu text-white" style="background-color: steelblue; color: white ">
                                    <li><a class="dropdown-item" href="~/Admin/Logout">Đăng xuất</a></li>
                                </ul>
                            </li>

                        }
                        <li class="nav-item" >
                            <a class="nav-link" href="@Url.Action("Index","Category")">
                                <span class="nav-link-text">Danh mục sách</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index", "Publisher")">
                                <span class="nav-link-text">Nhà xuất bản</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index","Author")">
                                <span class="nav-link-text">Tác giả</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index","Book")">
                                <span class="nav-link-text">Sách</span>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index","Customer")">
                                <span class="nav-link-text">Tài khoản</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index","DONHANGs")">
                                <span class="nav-link-text">Đơn hàng</span>
                            </a>
                        </li>
                        <li class="nav-item" style="border-bottom: 3px solid; border-color: blanchedalmond; ">
                            <a class="nav-link" href="@Url.Action("ThongKe","Admin")">
                                <span class="nav-link-text">Thông kê</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
    <div class="app-wrapper" , style="background-color: white; margin-top: -15px; height: 905px">
        <div class="app-content pt-3 p-md-3 p-lg-4">
            <div class="container-xl">
                @RenderBody()
            </div>
        </div>
    </div>
</body>
</html>

MiniBook/MiniBook/Views/Shared/_LayoutAllBook.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    <div class="container" style="background-color: #fcfcf3">
        <nav class="navbar navbar-expand-lg " >
            <div class="container-fluid">
                <a class="navbar-brand" href="~/MBook/index">
                    <img src="~/Images/Logo.png" alt="Logo" width="130" height="24" class="d-inline-block align-text-top">
                </a>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="#">Liên hệ</a>
                        </li>
                        @if (@Session["CusName"] == null)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-toggle="dropdown">
                                    Tài khoản
                                </a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="@Url.Action("Login","Customer")">Đăng nhập</a>
                                    <a class="dropdown-item" href="@Url.Action("Register","Customer")">Đăng kí</a>
                                </div>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-toggle="dropdown">
                                    @Session["CusName"]
                                </a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="@Url.Action("LichSuDonHang", "DONHANGs",new { id = Session["IDCus"]})">Lịch sử mua hàng</a>
                                    <a class="dropdown-item" href="~/Customer/Logout">Đăng xuất</a>
                                </div>
                            </li>
                        }
                    </ul>
                    <div class="navbar-brand">
                        @Html.Action("GioHangPartial", "GioHang")
                    </div>
                    <form class="d-flex" action="~/MBook/AllBook" role="search">
                        <input class="form-control me-2" type="search" name="searchString" placeholder="Nhập tên sách" aria-label="searchString">
                        <button class="btn btn-outline-success" type="submit">Tìm</button>
                    </form>
                </div>
            </div>
        </nav>
        <hr />
        <div style="background-color: #fcfcf3">
            <div class="col-12">
                @Html.Action("GetCategories", "MBook")
                @RenderBody()
            </div>
        </div>
        <div style="text-align: center; background-color: #fcfcf3; padding-top: 30px; font-weight: 500; font-size: 20px; padding-bottom: 30px; " class="footer">
            <span>Copyright © 2023 MiniBook</span>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MiniBook/MiniBook/Views/Shared/_LayoutHome.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body >
    <div class="container" style="background-color: #fcfcf3;">
        <nav class="navbar navbar-expand-lg  bg-transparent">
            <div class="container-fluid">
                <a class="navbar-brand" href="~/MBook/index">
                    <img src="~/Images/Logo.png" alt="Logo" width="130" height="24" class="d-inline-block align-text-top">
                </a>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="#">Liên hệ</a>
                        </li>
                        @if (@Session["CusName"] == null)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-toggle="dropdown">
                                    Tài khoản
                                </a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="@Url.Action("Login","Customer")">Đăng nhập</a>
                                    <a class="dropdown-item" href="@Url.Action("Register","Customer")">Đăng kí</a>
                                </div>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-toggle="dropdown">
                                    @Session["CusName"]
                                </a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="@Url.Action("LichSuDonHang", "DONHANGs",new { id = Session["IDCus"]})">Lịch sử mua hàng</a>
                                    <a class="dropdown-item" href="~/Customer/Logout">Đăng xuất</a>
                                </div>
                            </li>
                        }

                    </ul>
                    <div style="padding-right:1%" class="navbar-brand">
                        @Html.Action("GioHangPartial", "GioHang")
                    </div>
                    <form class="d-flex" action="~/MBook/AllBook" role="search">
                        <input class="form-control me-2" type="search" name="searchString" placeholder="Nhập tên sách" aria-label="searchString">
                        <button class="btn btn-outline-success" type="submit">Tìm</button>
                    </form>

                </div>
            </div>
        </nav>
        <hr />
        <br />
        <div style="background-color: #fcfcf3">
            <div class="col-md-12">

                @RenderBody()
            </div>
        </div>
        <div style="text-align: center; background-color: #fcfcf3; padding-top: 30px; font-weight: 500; font-size: 20px; padding-bottom: 30px; " class="footer">
            <span>Copyright © 2023 MiniBook</span>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>