MiniBook/MiniBook/Models/CHITIETDONHANG.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDONHANG
    {
        public int IDDonHang { get; set; }
        public int IDSach { get; set; }
        public Nullable<int> SL { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<double> ThanhTien { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
        public virtual SACH SACH { get; set; }
    }
}

MiniBook/MiniBook/Models/DONHANG.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONHANG()
        {
            this.CHITIETDONHANGs = new HashSet<CHITIETDONHANG>();
        }
    
        public int IDDonHang { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<double> TongTien { get; set; }
        public Nullable<System.DateTime> NgayGiao { get; set; }
        public string DiaChiNhan { get; set; }
        public string SDTNhan { get; set; }
        public string TenNguoiNhan { get; set; }
        public Nullable<System.DateTime> NgayGuiHang { get; set; }
        public string HTGiaoHang { get; set; }
        public string HTThanhToan { get; set; }
        public string TrangThai { get; set; }
        public Nullable<int> IDKhachHang { get; set; }
        public string Voucher { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONHANG> CHITIETDONHANGs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual VOUCHER VOUCHER1 { get; set; }
    }
}

MiniBook/MiniBook/Controllers/DONHANGsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MiniBook.Models;

namespace MiniBook.Controllers
{
    public class DONHANGsController : Controller
    {
        private BOOKSTOREEntities db = new BOOKSTOREEntities();

        // GET: DONHANGs
        public ActionResult Index()
        {
            if (Session["Admin"] == null)
                return RedirectToAction("Login", "Admin");
            var dONHANGs = db.DONHANGs.OrderByDescending(d => d.NgayDat).Include(d => d.KHACHHANG).Include(d => d.VOUCHER1);
            return View(dONHANGs.ToList());
        }
        public ActionResult LichSuDonHang(int id)
        {
            var dsDon = db.DONHANGs.Where(d => d.IDKhachHang == id).ToList();
            return View(dsDon);
        }
        public ActionResult DanhSachSanPham(int id)
        {
            
            var dss = db.CHITIETDONHANGs.Where(d => d.IDDonHang == id).ToList();
            return View(dss);
        }
        // GET: DONHANGs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DONHANG dONHANG = db.DONHANGs.Find(id);
            if (dONHANG == null)
            {
                return HttpNotFound();
            }
            return View(dONHANG);
        }

        // GET: DONHANGs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DONHANG dONHANG = db.DONHANGs.Find(id);
            if (dONHANG == null)
            {
                return HttpNotFound();
            }
            ViewBag.IDKhachHang = new SelectList(db.KHACHHANGs, "IDKhachHang", "Ten", dONHANG.IDKhachHang);
            ViewBag.Voucher = new SelectList(db.VOUCHERs, "Ma", "Ma", dONHANG.Voucher);
            return View(dONHANG);
        }

        // POST: DONHANGs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDDonHang,NgayDat,TongTien,NgayGiao,DiaChiNhan,SDTNhan,TenNguoiNhan,NgayGuiHang,HTGiaoHang,HTThanhToan,TrangThai,IDKhachHang,Voucher")] DONHANG dONHANG)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dONHANG).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IDKhachHang = new SelectList(db.KHACHHANGs, "IDKhachHang", "Ten", dONHANG.IDKhachHang);
            ViewBag.Voucher = new SelectList(db.VOUCHERs, "Ma", "Ma", dONHANG.Voucher);
            return View(dONHANG);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult ChiTietDonHang(int id)
        {
            if (Session["Admin"] == null)
                return RedirectToAction("Login", "Admin");
            var ctDonHang = db.CHITIETDONHANGs.Where(ct => ct.IDDonHang == id).ToList();
            return View(ctDonHang);
        }
    }
}

MiniBook/MiniBook/Views/DONHANGs/ChiTietDonHang.cshtml
@model IEnumerable<MiniBook.Models.CHITIETDONHANG>

@{
    ViewBag.Title = "ChiTietDonHang";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Thông tin chi tiết đơn hàng </h2>
<table class="table">
    <tr>
        <th>
            Tên sách
        </th>
        <th>
            Số lượng
        </th>
        <th>
            Đơn giá
        </th>
        <th>
            Thành tiền
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.SACH.TenSach)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SL)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DonGia)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ThanhTien)
        </td>
    </tr>
}

</table>
<p style="text-align:center; padding-top: 20px">
    @Html.ActionLink("Trở về", "Index", null, new { @class = "btn btn-outline-secondary" })
</p>

MiniBook/MiniBook/Views/DONHANGs/DanhSachSanPham.cshtml
@model IEnumerable<MiniBook.Models.CHITIETDONHANG>

@{
    ViewBag.Title = "DanhSachSanPham";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}
<h2>Danh sách sản phẩm </h2>
<table class="table">
    <tr>
        <th>
            Tên sách
        </th>
        <th>
            Số lượng
        </th>
        <th>
            Đơn giá
        </th>
        <th>
            Thành tiền
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SACH.TenSach)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SL)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DonGia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ThanhTien)
            </td>
        </tr>
    }

</table>
<p style="text-align:center; padding-top: 20px">
    @Html.ActionLink("Trở về", "LichSuDonHang", "DONHANGs", new { id = Session["IDCus"] }, new { @class = "btn btn-outline-secondary" })
</p>

MiniBook/MiniBook/Views/DONHANGs/Details.cshtml
@model MiniBook.Models.DONHANG
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="text-align:center">Chi tiết đơn hàng </h2>
<hr />
<div>

    <div class="dl-horizontal">
        <div class="row">
            <div class="col-md-3 row-title">
                ID đơn hàng:
            </div>
            <div class="col-md-9">
                @Html.DisplayFor(model => model.IDDonHang)
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 row-title">
                Ngày đặt:
            </div>
            <div class="col-md-9">
                @Html.DisplayFor(model => model.NgayDat)
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 row-title">
                Ngày giao:
            </div>
            <div class="col-md-9">
                @Html.DisplayFor(model => model.NgayGiao)
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 row-title">
                Tổng tiền:
            </div>
            <div class="col-md-9">
                @Html.DisplayFor(model => model.TongTien)
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 row-title">
                Tên người nhận:
            </div>
            <div class="col-md-9">
                @Html.DisplayFor(model => model.TenNguoiNhan)
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 row-title">
                Địa chỉ nhận:
            </div>
            <div class="col-md-9">
                @Html.DisplayFor(model => model.DiaChiNhan)
            </div>
        </div>

        <div class="row">
            <div class="col-md-3 row-title">
                Số điện thoại nhận:
            </div>
            <div class="col-md-9">
                @Html.DisplayFor(model => model.SDTNhan)
            </div>
        </div>

        <div class="row">
            <div class="col-md-3 row-title">
                Hình thức giao hàng:
            </div>
            <div class="col-md-9">
                @Html.DisplayFor(model => model.HTGiaoHang)
            </div>
        </div>

        <div class="row">
            <div class="col-md-3 row-title">
                Hình thức thanh toán:
            </div>
            <div class="col-md-9">
                @Html.DisplayFor(model => model.HTThanhToan)
            </div>
        </div>

        <div class="row">
            <div class="col-md-3 row-title">
                Ngày gửi hàng:
            </div>
            <div class="col-md-9">
                @Html.DisplayFor(model => model.NgayGuiHang)
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 row-title">
                Tình trạng đơn hàng:
            </div>
            <div class="col-md-9">
                @Html.DisplayFor(model => model.TrangThai)
            </div>
        </div>

        <div class="row">
            <div class="col-md-3 row-title">
                Tên tài khoản đặt hàng:
            </div>
            <div class="col-md-9">
                @Html.DisplayFor(model => model.KHACHHANG.Ten)
            </div>
        </div>

        <div class="row">
            <div class="col-md-3 row-title">
                Voucher đã dùng:
            </div>
            <div class="col-md-9">
                @Html.DisplayFor(model => model.VOUCHER1.Ma)
            </div>
        </div>

    </div>
</div>

<p style="text-align:center; padding-top: 20px">
    @Html.ActionLink("Cập nhật trạng thái", "Edit", new { id = Model.IDKhachHang }, new { @class = "btn btn-outline-warning" }) |
    @Html.ActionLink("Chi tiết sản phẩm", "ChiTietDonHang", new { id = Model.IDDonHang }, new { @class = "btn btn-outline-info" }) |
    @Html.ActionLink("Trở về", "Index", null, new { @class = "btn btn-outline-secondary" })
</p>

MiniBook/MiniBook/Views/DONHANGs/Edit.cshtml
@model MiniBook.Models.DONHANG

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<h2 style="text-align:center">Chỉnh sửa thông tin đơn hàng </h2>

<hr />


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDDonHang)

        <div class="form-group">
           Ngày đặt
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayDat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayDat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Tổng tiền
            <div class="col-md-10">
                @Html.EditorFor(model => model.TongTien, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TongTien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Ngày giao
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayGiao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayGiao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Địa chỉ nhận
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChiNhan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChiNhan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Số điện thoại nhận
            <div class="col-md-10">
                @Html.EditorFor(model => model.SDTNhan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SDTNhan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Tên người nhận
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenNguoiNhan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenNguoiNhan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Ngày gửi hàng 
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayGuiHang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayGuiHang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Hình thức giao hàng
            <div class="col-md-10">
                @Html.EditorFor(model => model.HTGiaoHang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HTGiaoHang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Hình thức thanh toán
            <div class="col-md-10">
                @Html.EditorFor(model => model.HTThanhToan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HTThanhToan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
           Trạng thái đơn hàng
            <div class="col-md-10">
                <select name="TrangThai" >
                    <option name="TrangThai" value="@Model.TrangThai">@Model.TrangThai</option>
                    @if (Model.TrangThai == "Chờ xác nhận")
                    {
                        <option name="TrangThai" value="Đã xác nhận - Đang chuẩn bị hàng">Đã xác nhận - Đang chuẩn bị hàng</option>
                        <option name="TrangThai" value="Đã gửi hàng">Đã gửi hàng</option>
                        <option name="TrangThai" value="Đã hủy">Đã hủy</option>
                    }
                    else if (Model.TrangThai == "Đã xác nhận - Đang chuẩn bị hàng")
                    {
                        <option name="TrangThai" value="Đã gửi hàng">Đã gửi hàng</option>
                        <option name="TrangThai" value="Đã hủy">Đã hủy</option>
                    }
                    else if (Model.TrangThai == "Đã gửi hàng")
                    {
                        <option name="TrangThai" value="Đã hoàn thành">Đã hoàn thành</option>
                        <option name="TrangThai" value="Đã hủy">Đã hủy</option>
                    }
                </select>
            </div>
        </div>

        <div class="form-group">
            Khách hàng
            <div class="col-md-10">
                @Html.DropDownList("IDKhachHang", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDKhachHang, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-actions no-color" style="text-align:center; padding-top: 20px">
            <input type="submit" value="Lưu" class="btn btn-success" /> |
            @Html.ActionLink("Trở về", "Index", null, new { @class = "btn btn-outline-secondary" })
        </div>
    </div>
}

MiniBook/MiniBook/Views/DONHANGs/Index.cshtml
@model IEnumerable<MiniBook.Models.DONHANG>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<h2 style="text-align:center">Danh sách đơn hàng</h2>
<hr />
<table class="table">
    <tr>
        <th>
            ID
        </th>
        <th>
            Ngày đặt
        </th>
        <th>
            Tổng tiền
        </th>
        <th>
            Số điện thoại nhận
        </th>
        <th>
            Trạng thái
        </th>
        <th>
            Tên khách hàng
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IDDonHang)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgayDat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TongTien)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SDTNhan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TrangThai)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.KHACHHANG.Ten)
            </td>
            <td>
                @Html.ActionLink("Chỉnh sửa", "Edit", new { id = item.IDDonHang }, new { @class = "btn btn-outline-warning" }) |
                @Html.ActionLink("Chi tiết", "Details", new { id = item.IDDonHang }, new { @class = "btn btn-outline-info" })
            </td>
        </tr>
    }

</table>

MiniBook/MiniBook/Views/DONHANGs/LichSuDonHang.cshtml
@model IEnumerable<MiniBook.Models.DONHANG>

@{
    ViewBag.Title = "LichSuDonHang";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}

<h2 style="text-align:center">Lịch sử đơn hàng</h2>
<hr />
<table class="table">
    <tr>
        <th>
            Ngày đặt
        </th>
        <th>
            Ngày gửi
        </th>
        <th>
            Ngày giao
        </th>
        <th>
            Hình thức giao hàng
        </th>
        <th>
            Tổng tiền
        </th>
        <th>
            Trạng thái
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NgayDat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgayGuiHang)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgayGiao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HTGiaoHang)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TongTien)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.TrangThai)
            </td>
            <td>
                @Html.ActionLink("Sản phẩm", "DanhSachSanPham", new { id = item.IDDonHang }, new { @class = "btn btn-outline-info" })
            </td>
        </tr>
    }

</table>